FIREBASE_DATABASE_URL = 'https://ecs-oprec-default-rtdb.asia-southeast1.firebasedatabase.app/'
FIREBASE_CREDENTIAL_PATH = 'key.json'

SERIAL_PORT = 'COM5'
BAUD_RATE = 115200
SERIAL_TIMEOUT = 2

MODEL_PATH = 'models/pahangv16_1_200_32_s.pt'
CONFIDENCE_THRESHOLD = 0.5
FILTER_IMAGE = False

L1 = 9.2
L2 = 13.5
L3 = 14.7
L4 = 8.7

INITIAL_ANGLES = (180, 80.0, 160.0)
INITIAL_EE_ANGLE = 90.0
GRAB_EE_ANGLE = 0.0

CALIBRATION_FILE = 'stereo_calib.npz'

MATCH_THRESHOLD_Y = 10
MATCH_THRESHOLD_CLASS = 0.8

MOVE_TO_OBJECT_DELAY = 3
GRAB_OBJECT_DELAY = 1
RETURN_TO_INITIAL_DELAY = 1
OPEN_EE_DELAY = 1 

Y_ADJUSTMENT = 20
Z_ADJUSTMENT = 3